import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const SUIT = localFont({
  src: [
    {
      path: "../../public/fonts/SUIT-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${SUIT.variable}`} lang="en">
      <body>{children}</body>
    </html>
  );
}
